/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { ServerRoute as ApiAuthCallbackGoogleServerRouteImport } from './routes/api/auth.callback.google'
import { ServerRoute as ApiAuthCallbackGithubServerRouteImport } from './routes/api/auth.callback.github'

const rootServerRouteImport = createServerRootRoute()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackGoogleServerRoute =
  ApiAuthCallbackGoogleServerRouteImport.update({
    id: '/api/auth/callback/google',
    path: '/api/auth/callback/google',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiAuthCallbackGithubServerRoute =
  ApiAuthCallbackGithubServerRouteImport.update({
    id: '/api/auth/callback/github',
    path: '/api/auth/callback/github',
    getParentRoute: () => rootServerRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/auth/callback/github': typeof ApiAuthCallbackGithubServerRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/callback/github': typeof ApiAuthCallbackGithubServerRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/callback/github': typeof ApiAuthCallbackGithubServerRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/callback/github' | '/api/auth/callback/google'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/callback/github' | '/api/auth/callback/google'
  id: '__root__' | '/api/auth/callback/github' | '/api/auth/callback/google'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthCallbackGithubServerRoute: typeof ApiAuthCallbackGithubServerRoute
  ApiAuthCallbackGoogleServerRoute: typeof ApiAuthCallbackGoogleServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/auth/callback/google': {
      id: '/api/auth/callback/google'
      path: '/api/auth/callback/google'
      fullPath: '/api/auth/callback/google'
      preLoaderRoute: typeof ApiAuthCallbackGoogleServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/callback/github': {
      id: '/api/auth/callback/github'
      path: '/api/auth/callback/github'
      fullPath: '/api/auth/callback/github'
      preLoaderRoute: typeof ApiAuthCallbackGithubServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthCallbackGithubServerRoute: ApiAuthCallbackGithubServerRoute,
  ApiAuthCallbackGoogleServerRoute: ApiAuthCallbackGoogleServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
